--
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Deployment
metadata:
  name: nginx-test
  namespace: itest
  labels:
    env: dev
  spec:
    selector:
      matchLabels:
        app: nginx-test
    template:
      metadata:
        labels:
          app: nginx-test


